"""customer and personal_loan_offer tables

Revision ID: 69f73cb79548
Revises: 2d9381e9890b
Create Date: 2020-02-07 07:27:33.394548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f73cb79548'
down_revision = '2d9381e9890b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('income', sa.Integer(), nullable=True),
    sa.Column('education', sa.Integer(), nullable=True),
    sa.Column('cc_avg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('family', sa.Integer(), nullable=True),
    sa.Column('cd_account', sa.Boolean(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_timestamp'), 'customer', ['timestamp'], unique=False)
    op.create_table('personal_loan_offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('predicted_response', sa.String(length=15), nullable=True),
    sa.Column('prediction_probability', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_response', sa.String(length=15), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_loan_offer_timestamp'), 'personal_loan_offer', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personal_loan_offer_timestamp'), table_name='personal_loan_offer')
    op.drop_table('personal_loan_offer')
    op.drop_index(op.f('ix_customer_timestamp'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
