"""empty message

Revision ID: 8d9c6ed09dd4
Revises: 69f73cb79548
Create Date: 2020-02-10 16:37:58.886799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9c6ed09dd4'
down_revision = '69f73cb79548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_import_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_import_file_name'), 'customer_import_file', ['name'], unique=False)
    op.create_index(op.f('ix_customer_import_file_timestamp'), 'customer_import_file', ['timestamp'], unique=False)
    op.add_column('customer', sa.Column('import_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customer', 'customer_import_file', ['import_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_column('customer', 'import_file_id')
    op.drop_index(op.f('ix_customer_import_file_timestamp'), table_name='customer_import_file')
    op.drop_index(op.f('ix_customer_import_file_name'), table_name='customer_import_file')
    op.drop_table('customer_import_file')
    # ### end Alembic commands ###
